/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author laispaivaportela
 */
import controller.Bingo; //classe Bingo
import javax.swing.DefaultListModel; //classe com modelos de lista
import java.util.ArrayList;
import java.util.List;

public class FrmBingo extends javax.swing.JFrame {
 Bingo bingo = new Bingo();    //instancia a classe "Bingo" (começa um bingo)
 DefaultListModel <String> model = new DefaultListModel<>(); //cria uma lista modelo
    /**
     * Creates new form FrmSorteio
     */
    public FrmBingo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jMenu3 = new javax.swing.JMenu();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        lblTitulo = new javax.swing.JLabel();
        btnSorteiaNumero = new javax.swing.JButton();
        lblNumeroSorteado = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstListaNumerosSorteados = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itmNovoBingo = new javax.swing.JMenuItem();

        jTextField1.setText("jTextField1");

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("bingo de domingo");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 255, 204));
        setLocation(new java.awt.Point(0, 0));

        lblTitulo.setFont(new java.awt.Font("Showcard Gothic", 0, 54)); // NOI18N
        lblTitulo.setText("Bingo De Domingo");

        btnSorteiaNumero.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        btnSorteiaNumero.setText("Girar a roleta");
        btnSorteiaNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSorteiaNumeroActionPerformed(evt);
            }
        });

        lblNumeroSorteado.setFont(new java.awt.Font("Cambria Math", 0, 230)); // NOI18N
        lblNumeroSorteado.setText("0");

        lstListaNumerosSorteados.setBackground(new java.awt.Color(255, 255, 204));
        lstListaNumerosSorteados.setFont(new java.awt.Font("Arial", 0, 28)); // NOI18N
        jScrollPane1.setViewportView(lstListaNumerosSorteados);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\laisp_omzy4s1\\OneDrive\\Documentos\\NetBeansProjects\\BingoDesafio\\resources\\bingoum.png")); // NOI18N
        jLabel1.setToolTipText("");

        jMenu1.setText("Bingo");
        jMenu1.setToolTipText("");

        itmNovoBingo.setText("Novo Bingo");
        itmNovoBingo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmNovoBingoActionPerformed(evt);
            }
        });
        jMenu1.add(itmNovoBingo);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNumeroSorteado, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSorteiaNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblNumeroSorteado, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSorteiaNumero, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                                .addGap(41, 41, 41))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(61, 61, 61))))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSorteiaNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSorteiaNumeroActionPerformed

        int numeroSorteado = bingo.sorteiaNumero(); //atribui o numero sorteado à variável
        String numeroSorteadoStr = Integer.toString(numeroSorteado); //transforma o numero sorteado (int) em String
        lblNumeroSorteado.setText(numeroSorteadoStr); //imprime no label o número sorteado

        lstListaNumerosSorteados.setModel(model); //atribui o modelo
        model.add(0, numeroSorteadoStr); //adiciona elemento (numero sorteado) na posição 0

    }//GEN-LAST:event_btnSorteiaNumeroActionPerformed

    private void itmNovoBingoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmNovoBingoActionPerformed
     lblNumeroSorteado.setText("0"); //imprime no label o numero zero (igual no começo)
     model.clear();
    }//GEN-LAST:event_itmNovoBingoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmBingo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmBingo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmBingo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmBingo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmBingo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSorteiaNumero;
    private javax.swing.JMenuItem itmNovoBingo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblNumeroSorteado;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JList<String> lstListaNumerosSorteados;
    // End of variables declaration//GEN-END:variables
}
